version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - PYTHONPATH=${PYTHONPATH}
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - web_app_log:/code/logs

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  web_app_log: