apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNw==
  MONGODB_DATABASE: bmV3c19hZ2dyZWdhdG9yX2Ri
  SECRET_KEY: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
  ALGORITHM: SFMyNTY=
  ACCESS_TOKEN_EXPIRE_MINUTES: NjA=
  PYTHONPATH: L2NvZGU=
